### ISSUE TITLE
System.OutOfMemoryException with 700+ k rows

### ISSUE THREAD

**Issue by miyconst** [Starcounter/ODataApi#31] opened 2018-01-19 08:43 UTC
@un-tone is there anything wen can do to increase the amount of data ODataApi is able to handle?

```
[DataSource.Error] OData: Request failed: The remote server returned an error: (500) Internal Server Error. (System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
  at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
  at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
  at ODataApi.OData.Handlers.SelectSetResponseHandler.Handle(Request request) in C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\ODataApi\src\ODataApi\OData\Handlers\SelectSetResponseHandler.cs:line 122
  at ODataApi.Api.MainHandlers.HandleDataRequest(Request request) in C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\ODataApi\src\ODataApi\Api\MainHandlers.cs:line 39
  at ODataApi.Api.MainHandlers.<Register>b__0_2(String path, Request request) in C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\ODataApi\src\ODataApi\Api\MainHandlers.cs:line 19
  at lambda_method(Closure , Request , IntPtr , IntPtr )
  at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 201
  at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
  at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-10439\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 348
HResult=-2147024882

More information about this error may be available in the server error log.)
```

**Comment by un-tone** [comment] 2018-01-19 11:09
We should limit the number of rows in responses and use `@odata.nextLink` here:
https://github.com/StarcounterApps/ODataApi/blob/6770cde60a0d8bdf7106159c29804c4d23344962/src/ODataApi/OData/Handlers/SelectSetResponseHandler.cs#L110

**Comment by un-tone** [comment] 2018-01-19 11:12
Using this way a client after receiving the first part of data will know which request it should make to get the next part. AFAIR Power BI work so.

**Comment by miyconst** [comment] 2018-01-19 12:29
@un-tone let's go the way you propose, but this is a low priority issue.

**Comment by un-tone** [comment] 2018-04-06 22:24
PR https://github.com/Starcounter/ODataApi/pull/33

**Comment by un-tone** [comment] 2018-04-09 17:57
The changes are applied. @miyconst do you have some ready playground where you could check the last version of the app? Can I ask you to do it or should I try to check it myself?

**Comment by miyconst** [comment] 2018-04-09 18:28
@atifwaqar would you volunteer to check the solution?

**Comment by un-tone** [comment] 2018-04-22 09:46
The issue is resolved. I checked it with provided by @atifwaqar service.
Closing...

**Closed by un-tone** 2018-04-22 09:46 UTC
Labels: P/Low, enhancement
